name: Generate Feed

on:
  schedule:
    - cron: "0 */1 * * *"   # запуск раз на 6 годин
  workflow_dispatch:        # можливість запускати вручну

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run script
        run: python generate_price_feed.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: feed_prices
          path: feed_prices.xml
